### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by Ilak0121** [Ilak0121/uc_os2#4]
- [ ] idle process not process

- [ ] preempt process 2 not completeing
-------------------------------------------------
- [ ] time exceed handling implementaion
